### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by patrikvolka** [Lombiq/Orchard-Privacy#28]
Hi, I have added Lombiq.Privacy to my Orchard Core project using Nuget.org.
I don't know where I'm doing wrong, but I can't locate the texts in Lombiq.Privacy.
Please advise where I should save the localization file Lombiq.Privacy.po, or some sample file Lombiq.Privacy.po

Thanks

**Comment by Piedone** [comment]
You should be able to use the locations here (except `[ModuleLocation]`): https://docs.orchardcore.net/en/latest/docs/reference/modules/Localize/#po-files-locations Just be sure to use "Lombiq.Privacy" as `ModuleId`. Doesn't this work?

Note that you'll need to generate PO files from the module's source though.

Also, do you want to localize the admin UI of the module, right? Because for the frontend you don't need PO localization.

**Comment by Piedone** [comment]
Assuming there are no issues.
